name: CICD pipeline

trigger:
  - master
  - feature/*

pool: default

stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'bootcampapp2'
              repository: 'bootcampapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
      