name: CICD pipeline

trigger:
  - master
  - feature/*

pool: default

stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'bootcampapp2'
              repository: 'bootcampapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
      
  
  - stage: DeployToStaging
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    variables:
      - group: staging  
    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'staging'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: printAllVariables@1
            - task: KubernetesManifest@0
              inputs:
                action: 'createSecret'
                kubernetesServiceConnection: 'cluster'
                secretType: 'generic'
                secretName: 'secret.yml'
                secretArguments: '--from-literal=COOKIE_ENCRYPT_PWD=$(COOKIE_ENCRYPT_PWD) --from-literal=HOST=$(HOST) --from-literal=PORT=$(PORT) --from-literal=NODE_ENV=$(NODE_ENV) --from-literal=HOST_URL=$(HOST_URL) --from-literal=OKTA_CLIENT_ID=$(OKTA_CLIENT_ID) --from-literal=OKTA_CLIENT_SECRET=$(OKTA_CLIENT_SECRET) --from-literal=OKTA_ORG_URL=$(OKTA_ORG_URL)  --from-literal=PGHOST=$(PGHOST) --from-literal=PGUSERNAME=$(PGUSERNAME) --from-literal=PGDATABASE=$(PGDATABASE) --from-literal=PGPASSWORD=$(PGPASSWORD)  --from-literal=PGPORT=$(PGPORT)'
          
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                namespace: default
                kubernetesServiceConnection: 'staging-StagingKubernetesCluster-default-1659387810057'
                manifests: |
                             $(system.defaultworkingdirectory)/manifests/deployment.yml 
                             $(system.defaultworkingdirectory)/manifests/service.yml
                         #    $(system.defaultworkingdirectory)/manifests/ingress.yml
                
                containers: '$(containerRegistry)/$(imageRepository):$(tag)'
                
            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'staging-StagingKubernetesCluster-default-1659387810057'
                namespace: default
                command: 'apply'
                useConfigurationFile: true
                configuration: 'manifests/deployment.yml'
                secretType: 'generic'
                secretName: 'secrets.yml'