apiVersion : apps/v1
kind: Deployment
metadata:
  name: bootcampapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcampapp
  template:
    metadata:
      labels:
        app: bootcampapp 
    spec:
      containers:
        - name: bootcampapp 
          image: bootcampapp2.azurecr.io/bootcampapp
          
          ports:
          - containerPort: 80
          
          envFrom:
          - secretRef:
             name: secret.yml